import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

// ═══════════════════════════════════════
// 1. PRECACHE — Static assets (auto-generated by vite-plugin-pwa)
// ═══════════════════════════════════════
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// ═══════════════════════════════════════
// 2. NAVIGATION FALLBACK — SPA offline support
//    All navigations fallback to cached /index.html
// ═══════════════════════════════════════
const navigationHandler = new NetworkFirst({
  cacheName: 'navigation-cache',
  networkTimeoutSeconds: 3,
  plugins: [
    new CacheableResponsePlugin({ statuses: [0, 200] })
  ]
})

registerRoute(
  new NavigationRoute(navigationHandler, {
    // Don't handle API or websocket paths
    denylist: [/^\/api\//, /^\/ws/]
  })
)

// ═══════════════════════════════════════
// 3. API GET — NetworkFirst with cache fallback
// ═══════════════════════════════════════
registerRoute(
  ({ url, request }) => url.pathname.startsWith('/api/') && request.method === 'GET',
  new NetworkFirst({
    cacheName: 'api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 5 * 60 // 5 minutes
      })
    ]
  })
)
// ═══════════════════════════════════════
// 4. API MUTATIONS — Background Sync queue
//    POST/PUT/DELETE yang gagal di-retry saat online
// ═══════════════════════════════════════
const bgSyncPlugin = new BackgroundSyncPlugin('api-mutation-queue', {
  maxRetentionTime: 24 * 60, // Retry up to 24 hours (in minutes)
  onSync: async ({ queue }) => {
    let entry
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request.clone())
        console.log('🔄 Background sync: replayed', entry.request.url)
      } catch (err) {
        console.error('🔄 Background sync failed, re-queuing:', err)
        await queue.unshiftRequest(entry)
        throw err // Let workbox know sync failed
      }
    }
    console.log('✅ Background sync: all queued requests replayed')
  }
})

// POST requests with background sync
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-mutations',
    plugins: [bgSyncPlugin]
  }),
  'POST'
)

// PUT requests with background sync
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-mutations',
    plugins: [bgSyncPlugin]
  }),
  'PUT'
)

// DELETE requests with background sync
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-mutations',
    plugins: [bgSyncPlugin]
  }),
  'DELETE'
)

// ═══════════════════════════════════════
// 5. GOOGLE FONTS — CacheFirst (long-lived)
// ═══════════════════════════════════════
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 })
    ]
  })
)

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 365 * 24 * 60 * 60 })
    ]
  })
)

// ═══════════════════════════════════════
// 6. IMAGES — StaleWhileRevalidate
// ═══════════════════════════════════════
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 })
    ]
  })
)

// ═══════════════════════════════════════
// 7. SERVICE WORKER LIFECYCLE
// ═══════════════════════════════════════
self.addEventListener('install', () => {
  console.log('📦 Service Worker installed')
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  console.log('✅ Service Worker activated')
  event.waitUntil(self.clients.claim())
})

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
